# Generated by Django 4.1.7 on 2023-04-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selection',
            options={'ordering': ['owner'], 'verbose_name': 'Пользовательская выборка объявлений', 'verbose_name_plural': 'Пользовательские выборки объявлений'},
        ),
    ]
