# Generated by Django 4.1.7 on 2023-03-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('is_published', models.CharField(choices=[('TRUE', 'Опубликовано'), ('FALSE', 'Не опубликовано')], default='FALSE', max_length=5)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
