# Generated by Django 4.1.7 on 2023-03-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='Не указана', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.SET_DEFAULT, to='author.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='member', max_length=10),
        ),
    ]
